refactor: use namespace import to import "typescript"
JoshuaKGoldberg/ts-api-utils pull request #588
Opened 2024-11-25 15:10 UTC by fisker

## PR Checklist

- [ ] Addresses an existing open issue: fixes #000
- [ ] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/ts-api-utils/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [ ] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/ts-api-utils/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

In build script of Prettier, we transform the typescript package to ESM for better tree-shake, then we rewrite "import"s
 from `ts-api-utils`, do you think it's acceptable to use namespace import here? so we don't need rewrite these "import"s.

2024-11-25 15:53 UTC, JoshuaKGoldberg requested changes
I'm fine with this, but:

* Would want to hear from @RebeccaStevens as they've been doing a bunch of fantastic work improving the build system (as you've seen)
* If this is 👍, there should be a lint rule to stop new default imports from being added in the future

2024-11-25 16:21 UTC, fisker commented
Looks like it's a bad idea, the original package can't be namespace imported

```
> Object.keys(await import('typescript'))
[ 'default' ]
```

2024-11-25 16:21 UTC, closed without merging

2025-03-19 05:35 UTC, fisker commented
Looks like typescript support namespace import now.

```js
> Object.keys(await import('typescript')).length
2238
```

2025-03-19 08:25 UTC, RebeccaStevens commented
Seems good to me. We just need to check that this is valid in all our supported versions of TypeScript